site_name: My Docs

nav:
  - index.md
  - "My page": page1.md
  - API:
    #- api/*
    #- "myfunction": api/myfunction.md
    - api/myfunction.md
    - api/myfunction2.md
plugins:
  - search
  - mkdocstrings
  - gen-files:
      scripts:
        - scripts/basic_script.py
          
